name: Flutter CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: macOS

    steps:
      - uses: actions/checkout@v4

      # ✅ Setup Java for Android build
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # ✅ Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.6' # ← Match your local "flutter --version"
          cache: true

      # ✅ Accept Android SDK licenses
      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses || true

      # ✅ Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # ✅ Run analyzer & tests
      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # ✅ Build APK (release)
      - name: Build APK
        run: flutter build apk --release

      # ✅ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
