name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, flutter, sequoia]  # 👈 targets your custom labels
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        run: |
          export PATH="$PATH:$HOME/flutter/bin"
          flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build iOS
        run: flutter build ios --no-codesign

      - name: Build Android
        run: flutter build apk
